# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MovieApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MovieApp
  pod 'Alamofire', '~> 5.4.3'
  pod 'CocoaLumberjack/Swift', '~> 3.7.2'
  pod 'SwiftLint', '~> 0.43.1'
  pod 'Kingfisher', '7.0'

end
